git add 006.png
git add 011.png
git add README.md
git add check.ipynb
git add config/
git add data_kubric/
git add data_objaverse/
git add data_omniobject3d/
git add dataset/
git add demo.py
git add ds_config.json
git add eval.py
git add model/
git add real_image/
git add requirements.txt
git add scripts/
git add train.py
git add train_deepspeed.py
git add utils/