        modified:   assets/real_image/real_masked/0_0.png
        modified:   assets/real_image/real_masked/0_1.png
        modified:   assets/real_image/real_masked/0_2.png
        deleted:    config/__pycache__/config.cpython-38.pyc
        modified:   config/config.py
        modified:   config/objaverse/train_224.yaml
        deleted:    dataset/__pycache__/kubric.cpython-38.pyc
        modified:   dataset/objaverse.py
        modified:   demo.sh
        modified:   eval.sh
        deleted:    model/__pycache__/backbone.cpython-38.pyc
        deleted:    model/__pycache__/encoder.cpython-38.pyc
        deleted:    model/__pycache__/lifting.cpython-38.pyc
        deleted:    model/__pycache__/model.cpython-38.pyc
        deleted:    model/__pycache__/neck.cpython-38.pyc
        deleted:    model/__pycache__/render_module.cpython-38.pyc
        deleted:    model/__pycache__/volume_render.cpython-38.pyc
        modified:   model/base_module/__pycache__/cross_attention.cpython-38.pyc
        modified:   model/external/__pycache__/perceptual_loss.cpython-38.pyc
        modified:   model/lifting.py
        modified:   model/render_module.py
        modified:   model/volume_render.py
        modified:   requirements.txt
        deleted:    scripts/__pycache__/evaluator.cpython-38.pyc
        deleted:    scripts/__pycache__/trainer.cpython-38.pyc
        modified:   scripts/demo.py
        modified:   scripts/evaluator.py
        modified:   scripts/trainer.py
        modified:   train.py
        modified:   train.sh
